kind: TrafficTarget
apiVersion: access.smi-spec.io/v1alpha3
metadata:
  name: bookstore
  namespace: stores
spec:
  destination:
    kind: ServiceAccount
    name: bookstore
    namespace: stores
  sources:
    - kind: ServiceAccount
      name: bookbuyer
      namespace: bookbuyer
    - kind: ServiceAccount
      name: bookthief
      namespace: bookthief
  rules:
    - kind: HTTPRouteGroup
      name: stores-service-routes
      matches:
        - buy
        # - steal

---

kind: TrafficTarget
apiVersion: access.smi-spec.io/v1alpha3
metadata:
  name: moviestore
  namespace: stores
spec:
  destination:
    kind: ServiceAccount
    name: moviestore
    namespace: stores
  sources:
    - kind: ServiceAccount
      name: bookbuyer
      namespace: bookbuyer
    - kind: ServiceAccount
      name: bookthief
      namespace: bookthief
  rules:
    - kind: HTTPRouteGroup
      name: stores-service-routes
      matches:
        - buy

---
apiVersion: specs.smi-spec.io/v1alpha4
kind: HTTPRouteGroup
metadata:
  name: stores-service-routes
  namespace: stores
spec:
  matches:
    - name: buy
      pathRegex: "/api/buy"
      methods:
        - GET
    - name: steal
      pathRegex: "/api/steal"
      methods:
        - GET
