# Create moviestore Service Account
apiVersion: v1
kind: ServiceAccount
metadata:
  name: moviestore
  namespace: stores

---

# Create moviestore Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: moviestore
  namespace: stores
spec:
  replicas: 1
  selector:
    matchLabels:
      app: moviestore
  template:
    metadata:
      labels:
        app: moviestore        
    spec:
      serviceAccountName: moviestore    
      containers:
        - name: moviestore
          image: 0gis0/moviestore
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
              name: web
---

# Create moviestore Service
apiVersion: v1
kind: Service
metadata:
  name: moviestore
  namespace: stores
  labels:
    app: moviestore
spec:  
  ports:
  - port: 80
    targetPort: 3000
    name: moviestore-port
  selector:
    app: moviestore
