apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: osm-ingress
  namespace: bookthief
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
    - host: bookthief.<INGRESS_PUBLIC_IP>.nip.io
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: bookthief
                port:
                  number: 80

---

kind: IngressBackend
apiVersion: policy.openservicemesh.io/v1alpha1
metadata:
  name: bookthief-external-access
  namespace: bookthief
spec:
  backends:
    - name: bookthief
      port:
        number: 4001 # targetPort of the service
        protocol: http
  sources:
    - kind: Service
      name: osm-nginx-ingess-ingress-nginx-controller
      namespace: ingress-nginx
